sudo: required
services:
  - docker
before_install:
  - docker pull yglukhov/devel
script:
  - docker run -v "$(pwd):/project" -w /project yglukhov/devel nim --version
  - docker run -v "$(pwd):/project" -w /project yglukhov/devel nim e ./tests/tests.nims
